on: [push, pull_request]
name: GoFig
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload Coverage
      uses: codecov/codecov-action@v1.0.7
        with:
          file: ./coverage.out
          fail_ci_if_error: true
